name: Build and Deploy HydePHP Site

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Download HydePHP project files
        working-directory: docs
        run: |
          cp -r . ../tmp
          git clone https://github.com/hydephp/hyde.git ../hyde --depth 1
          cp -r ../hyde/* .
          rm _pages/index.blade.php _pages/404.blade.php
          cp -r ../tmp/* .
          rm -rf ../tmp
      - name: Setup Hyde site
        run: |
          mv docs/documentation.md docs/_pages/index.md
          mv docs/components.blade.php docs/resources/views/components.blade.php
          echo "name: HydePHP UI Kit
          load_app_styles_from_cdn: true
          use_play_cdn: true
          navigation:
            subdirectories: dropdown
          " > docs/hyde.yml

      - uses: hydephp/action@master
        with:
          deploy-to: "pages"
          directory: docs
          env-torchlight-token: ${{ secrets.TORCHLIGHT_TOKEN }}
